version: '3.5'
services:
  app:
    build: .
    container_name: api-app
    volumes:
      - '.:/app'
    depends_on:
      - mongo-db
    ports:
      - '8000:8000'
    environment:
      - ./env/.env
    networks:
      - app_network

  mongo-db:
    image: mongo:4.2.9-bionic
    container_name: mongo-db
    env_file:
      - ./.env.docker
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - data:/data/db
    ports:
      - 8004:27017
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  data:
